-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 17:25:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_loja` DEFAULT CHARACTER SET utf8 ;
USE `db_loja` ;

-- -----------------------------------------------------
-- Table `db_loja`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tipocliente` (
  `id_tipo_tipocliente` INT NOT NULL,
  `s_desc_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_tipocliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`cliente` (
  `id_cliente` INT NOT NULL,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `s_cpf_cliente` VARCHAR(11) NOT NULL,
  `d_nacs_cliente` DATE NULL,
  `i_tipo_clientel` INT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_tipocliente_idx` (`i_tipo_clientel` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipocliente`
    FOREIGN KEY (`i_tipo_clientel`)
    REFERENCES `db_loja`.`tipocliente` (`id_tipo_tipocliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
